### ISSUE TITLE
The number of atmosphere stars in truncated

### ISSUE THREAD

**Issue by mquandalle** [sungwoncho/meteor-icon#1]
Hi @sungwoncho,

I added the Meteor icon to the `mquandalle:jade` package: https://github.com/mquandalle/meteor-jade

But unfortunately the number of stars is truncated, so it displays `12` instead of `129` which is super depressing because I appear far less popular than I am :p

**Comment by sungwoncho** [comment]
The number of stars is displayed under the version number. `12` is a score we calculate from the most recent daily scores given by Atmosphere. So your icon displays the right amount of stars.

But I think this score `12` is rather meaningless to the end users. I am thinking about removing it. What do you think?
