### ISSUE TITLE
Proposal to simplify the icon

### ISSUE THREAD

**Issue by sungwoncho** [sungwoncho/meteor-icon#4]
The icon currently has too much information and there is a room for improvements in the visual department.

From Atmosphere's daily scores, we (1) draw the graph, (2) calculate 5-star rating, and (3) calculate our own score. I think making these three features optional can be beneficial for two reasons:
1. Icon will look a lot cleaner and easier to understand.
2. For many packages, those features almost always look less than stellar. Thus package authors are less likely to adopt the icon.

Note that I am not proposing to remove the feature altogether. We will keep them and they will still be available. We will probably iterate on them in the future. Below is the example summarizing the proposal.

Default (icon.meteor.com/package/iron:router):

![localhost_3000_package_iron_router](https://cloud.githubusercontent.com/assets/8265228/11011835/6be6ceb4-8540-11e5-992e-d7e7e05d1007.png)

Scores turned on (icon.meteor.com/package/iron:router?scores=true):

![localhost_3000_package_iron_router_scores_true](https://cloud.githubusercontent.com/assets/8265228/11011842/7dfec0d4-8540-11e5-8f93-0e5a9b759039.png)

**Comment by tomitrescak** [comment]
Looks very nice. Good job there!!! If you need help let me know!

On Monday, November 9, 2015, Sung Won Cho notifications@github.com wrote:

> The icon currently has too much information and there is a room for
> improvements in the visual department.
> 
> From Atmosphere's daily scores, we (1) draw the graph, (2) calculate
> 5-star rating, and (3) calculate our own score. I think making these three
> features optional can be beneficial for two reasons:
> 1. Icon will look a lot cleaner and easier to understand.
> 2. For many packages, those features almost always look less than
>    stellar. Thus package authors are less likely to adopt the icon.
> 
> Note that I am not proposing to remove the feature altogether. We will
> keep them and they will still be available. We will probably iterate in the
> future. Below is the example summarizing the proposal.
> 
> Default (icon.meteor.com/package/iron:router):
> 
> [image: localhost_3000_package_iron_router]
> https://cloud.githubusercontent.com/assets/8265228/11011835/6be6ceb4-8540-11e5-992e-d7e7e05d1007.png
> 
> Scores turned on (icon.meteor.com/package/iron:router?scores=true):
> 
> [image: localhost_3000_package_iron_router_scores_true]
> https://cloud.githubusercontent.com/assets/8265228/11011842/7dfec0d4-8540-11e5-8f93-0e5a9b759039.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sungwoncho/meteor-icon/issues/4.

## 

Tomi Trescak / Researcher
tomi.trescak@gmail.com / 0487 261 213

[image: Facebook]  https://www.facebook.com/tomi.trescak[image: Twitter]
https://twitter.com/tomitrescak[image: Google Plus]
https://plus.google.com/112630384447746070397[image: Youtube]
https://www.youtube.com/user/tomiiiino[image: Linkedin]
https://www.linkedin.com/pub/tomas-trescak/34/b92/801?domainCountryName=&csrfToken=ajax%3A3648494742469937801
 [image: skype]

**Comment by sungwoncho** [comment]
The feature is deployed. Feel free to leave feedback here.

**Comment by ianserlin** [comment]
This is a good change, the "5 star rating feature" was a bit of a black box and in most cases felt misleading.

**Comment by sungwoncho** [comment]
Thanks for the feedback. Closing this because the changes have been in effect for almost three months.
