### ISSUE TITLE
"xx downloads in the last year"

### ISSUE THREAD

**Issue by anbuselvan** [sungwoncho/meteor-icon#5]
The Flow Router has been released to public since Feb 2015, this year.
https://github.com/kadirahq/flow-router/releases?after=v1.1.2

The Meteor Icon says "13450 downloads in the last year", looks a bit odd.

<img width="415" alt="screen shot 2015-11-19 at 11 58 33 am" src="https://cloud.githubusercontent.com/assets/167158/11282662/59825d1e-8eb5-11e5-8c9c-c49b224d5d65.png">

**Comment by sungwoncho** [comment]
The data is fed from Atmosphere's official API. The payload includes `"installs-per-year":13450`.

The 'last year' means the period between the present time and one year earlier today. I personally don't find it misleading. However, re-open this issue and let me know if you have any better wording.
